version: 1.0.{build}

init:
- cmd: git config --global core.autocrlf false

environment:
  nodejs_version: 4.1.2

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install -g karma-cli
  - npm cache clean
  - npm install

build: off

test_script:
  - npm test
